# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM arm64v8/nginx:stable-alpine@sha256:cd4e768b609c7e878e205831099d223f044195965bc8ffc62a3fe45185442e40
