# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM arm64v8/nginx:stable-alpine@sha256:21fd91d2410238fad7594d2d507e6dcdbc415f1d60dfd33419fad8380550857d
