# This wraps the upstream nginx image so dependabot can watch it for changes.
# If https://github.com/dependabot/dependabot-core/issues/390 is addressed, we
# can just inline this into docker-compose.yml
FROM arm64v8/nginx:stable-alpine@sha256:1603f6af4a2e7f6c25c1cd0ef03f79032d55d278294a1fde80dd5d88eec6b3ee
